### ISSUE TITLE
Swagger Edit not working

### ISSUE THREAD

**Issue by jaskaran07** [comprodls/generator-dls#6]

**Comment by harishbisht8** [comment]
its a bug/issue on some swagger dependency side
https://github.com/swagger-api/swagger-editor/issues/295

**Comment by jaskaran07** [comment]
Okay, lets track it.

**Comment by harishbisht8** [comment]
sry for wrong issue
already logged issue
https://github.com/swagger-api/swagger-editor/issues/296

On Thu, Jan 15, 2015 at 11:35 PM, jaskaran07 <notifications@github.com>
wrote:

> Okay, lets track it.
>
> On Thu, Jan 15, 2015 at 11:30 PM, Harish Singh Bisht <
> notifications@github.com> wrote:
>
> > its a bug/issue on some swagger dependency side
> > swagger-api/swagger-editor#295
> > <https://github.com/swagger-api/swagger-editor/issues/295>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/comprodls/generator-dls/issues/6#issuecomment-70130747>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/comprodls/generator-dls/issues/6#issuecomment-70131504>
> .
>



-- 
Regards,
Harish Singh Bisht

**Comment by jaskaran07** [comment]
Thanks!! No problem
